/* =====================================================================
   STANDING ACTIONS (Court phase)
   ===================================================================== */
const ACTIONS=[
  { id:"patronize",label:"Patronize the Church",cool:2,
    hint:"gold to the altars buys the pulpit's blessing — each gift moving the clergy less than the last",
    cost:{gold:-30},fac:{clergy:+8,peasantry:+2},requires:S=>true,diminish:"clergy",
    chron:S=>`the Crown lavished gold upon the Church, and the pulpits of ${S.nation} preached its right to rule.`,
    out:["New chapels rise; old debts to the abbeys are forgiven. From every pulpit your name is blessed."]},
  { id:"fund_army",label:"Fund and drill the army",
    hint:"stronger arms — and a permanently heavier upkeep",
    cost:{gold:-36,arms:+12},fac:{officers:+7,peasantry:-3},requires:S=>true,
    chron:S=>`the Crown swelled and drilled its regiments; ${S.nation} grew formidable, and costly.`,
    out:["Recruiting sergeants work the squares. The army sharpens — and so does the standing bill."]},
  { id:"festival",label:"Hold a festival of the Crown",cool:2,
    hint:"a costly spectacle that quiets the realm for a season",
    cost:{gold:-26,stability:+9},fac:{peasantry:+5,aristocracy:+2},requires:S=>true,
    chron:S=>`${S.nation} was given over to festival; for one gilded season the realm agreed to be content.`,
    out:["Bread, wine and fireworks. The grievances go quiet beneath the noise — for a while."]},
  { id:"festival_realm",label:"Hold a festival of the realm",cool:2,
    hint:"fairs and feasts in every market town — the realm's own celebration, not the palace's",
    cost:{gold:-22,stability:+5},fac:{peasantry:+6,provinces:+5},requires:S=>true,
    chron:S=>`${S.nation} kept festival in every market town and parish; for a season the realm celebrated itself.`,
    out:["Fairs, wakes and harvest feasts from the capital to the border parishes. The palace pays; the country parties; the country remembers."]},
  { id:"privileges",label:"Grant the great houses new privileges",
    hint:"buys noble loyalty — and adds a permanent charge to your upkeep",
    cost:{gold:-14,stability:-4},fac:{aristocracy:+11,peasantry:-4,merchants:-3},requires:S=>true,
    effect:S=>{S.privileges++;},
    chron:S=>`the Crown showered the great houses with privileges; their loyalty was secured, and its burden settled downward.`,
    out:["Charters and exemptions. The dukes beam. The cost will be paid every year hereafter."]},
  { id:"trade",label:"Sponsor trade, guilds and roads",
    hint:"slow investment: raises the realm's wealth, lifting all future revenue",
    cost:{gold:-28},fac:{merchants:+8,provinces:+3},requires:S=>true,
    effect:S=>{S.development=clamp(S.development+6);},
    chron:S=>`the Crown poured coin into roads, guilds and harbours; the wealth of ${S.nation} deepened.`,
    out:["New roads, chartered fairs, dredged harbours. Richer realms are richer to tax."]},
  { id:"suppress",label:"Suppress dissent with the garrison",
    hint:"order by force. Forbidden once a charter binds the Crown",
    cost:{gold:-12,stability:+12},fac:{peasantry:-8,provinces:-6,officers:+2},
    requires:S=>!S.gov.charter,
    chron:S=>`the Crown answered discontent with the garrison; order returned, and a grievance was pressed into memory.`,
    out:["Soldiers in the squares, a curfew at dusk. The unrest subsides into a silence that is not loyalty."]},
  { id:"tax_decree",label:"Levy an emergency tax by decree",
    hint:"raw absolutism: gold now, resentment forever. Impossible once a chamber holds the purse",
    cost:{gold:+38,stability:-9},fac:{peasantry:-8,aristocracy:-4,merchants:-4},
    requires:S=>!rightsHeld(S).has("tax"),
    chron:S=>`the Crown levied an emergency tax by decree; the coffers filled, and so did the ledger of grievances.`,
    out:["The collectors ride out with a warrant and no one's consent. Gold flows in. So does resentment."]},
  { id:"tax_request",label:"Request an extraordinary grant from the chamber",
    hint:"lawful emergency revenue — if the chamber consents",
    cost:{},consent:"tax",requires:S=>rightsHeld(S).has("tax"),
    resolve:S=>{ const c=consentCheck(S,"tax");
      if(c.approve) return {cost:{gold:+34,stability:+2},chron:S=>`the ${c.inst.name} granted the Crown an extraordinary subsidy; revenue by consent proved sturdier than any by fear.`,
        out:"They debate, grumble, and vote it through. Money granted willingly stays granted."};
      return {cost:{gold:+6,stability:-3},fac:{aristocracy:-2},chron:S=>`the ${c.inst.name} refused the Crown's request, and only a thin, grudging sum was raised.`,
        out:"The chamber is in no mood to be generous. A fraction of the ask — and a lecture besides."};
    }},
  { id:"tour",label:"Tour the provinces in state",cool:3,
    hint:"the sovereign's presence soothes the far country",
    cost:{gold:-16,stability:+3},fac:{provinces:+8,peasantry:+3},requires:S=>true,
    chron:S=>`the Crown made a great progress through the provinces, and the far country remembered it had a sovereign.`,
    out:["Banners, feasts, petitions heard in person. The provinces, so often forgotten, feel seen."]},
  { id:"appoint",label:"Appoint capable ministers",cool:3,
    hint:"good administration steadies the realm and its books",
    cost:{gold:-10,stability:+5},fac:{merchants:+3},requires:S=>S.gov.cabinet,
    effect:S=>{S.development=clamp(S.development+3);},
    chron:S=>`the Crown filled its cabinet with able men, and the machinery of ${S.nation} turned more smoothly.`,
    out:["Ministers chosen for merit over blood. The paperwork of the realm stops rotting on desks."]},
  { id:"address_commons",label:"Address the lower chamber in person",cool:3,
    hint:"the crown — or the minister — speaks to the people's benches directly",
    gain:"+4 Stability, the common estates warm",
    cost:{gold:-6,stability:+4},fac:{peasantry:+4,merchants:+3},
    requires:S=>S.gov.institutions.some(i=>i.composition!=="nobility"),
    chron:S=>`the ${S.pm?S.pm.office:"Crown"} addressed the lower chamber in person, and the benches roared.`,
    out:["A speech from the bar of the house — plainly written, plainly meant. The wards repeat it for a season."]},
  { id:"dissolve",label:"Dissolve the chamber",cool:3,
    hint:"send them home and put the realm to the polls before its time",
    gain:"a fresh election — and a chamber reminded who summoned it",
    cost:{gold:-10,stability:-6},requires:S=>!!S.pm&&S.gov.crown.power>=30&&S.gov.institutions.length>0,
    resolve:S=>{ const fx={}; (composition[S.gov.institutions[0].composition]||[]).forEach(k=>{fx[k]=-6;});
      S._dissolutions=(S._dissolutions||0)+1;
      if(S._dissolutions>=3){ return {cost:{gold:-10,stability:-16},fac:fx,
        effect:S2=>{transferPower(S2,S2.gov.institutions[0],14);S2.legitPen=(S2.legitPen||0)+8;S2.nextElection=S2.turn;},
        chron:S2=>`the Crown dissolved the chamber for the third time in living memory, and the realm decided it had seen enough of that.`,
        out:"You send them home again. This time the country does not go quietly — and when the new chamber sits, it sits with powers the Crown did not intend to give it. There is a limit, and you have found it."};}
      return {cost:{gold:-10,stability:-6},fac:fx,effect:S2=>{S2.nextElection=S2.turn;},
        chron:S2=>`the Crown dissolved the chamber and called the realm to an early poll.`,
        out:"The doors are locked, the mace carried out, the writs issued. The benches go home furious — and the country will now say what it thinks of you, whether you asked or not."};}},
  { id:"refuse_ministry",label:"Refuse the chamber's ministry",cool:4,
    hint:"the winning benches propose; the Crown declines, and appoints its own",
    gain:"a ministry of your choosing — governing without a majority",
    cost:{stability:-8},requires:S=>!!S.pm&&S.gov.crown.power>=38,
    resolve:S=>{ const blocs=Object.keys(S.facs).filter(k=>S.facs[k].present&&k!==S.pm.bloc);
      const nb=blocs.sort((a,b)=>S.facs[b].mood-S.facs[a].mood)[0]||S.pm.bloc;
      return {cost:{stability:-8},fac:{aristocracy:+4},
        effect:S2=>{S2.pm.bloc=nb;S2.pm.holder=pmName();S2.pm.age=46+rand(14);S2.legitPen=(S2.legitPen||0)+9;S2._minority=true;},
        chron:S2=>`the Crown refused the chamber's choice of minister and appointed one of its own, to the fury of the benches.`,
        out:`The Crown will not have them. The ${S.facs[nb].name} take the seals instead, governing on sufferance and without a majority — which historically lasts about as long as the Crown's nerve does.`};}},
  { id:"legislate",label:"Pass a program of legislation",
    hint:"the ministry's agenda, put to the chamber — statecraft by majority",
    gain:"if the benches hold: +6 Stability, the realm develops, your bloc rallies",
    cost:{gold:-18},requires:S=>!!S.pm,
    resolve:S=>{ const gv=S.facs[S.pm.bloc];
      if(gv.mood>=45){ const fx={}; fx[S.pm.bloc]=+4;
        return {cost:{gold:-18,stability:+6},fac:fx,effect:S2=>{S2.development=clamp(S2.development+3);},
        chron:S2=>`the ${S2.pm.office}'s program passed the chamber, and the realm was governed by statute rather than whim.`,
        out:"Readings, divisions, assent. The program passes — the machinery of law doing what decree once did."}; }
      const fx={}; fx[S.pm.bloc]=-2;
      return {cost:{gold:-8,stability:-3},fac:fx,
        chron:S2=>`the ${S2.pm.office}'s program stalled in a restless chamber.`,
        out:"Your own benches waver and the program dies in committee. A ministry that cannot legislate is a ministry on notice."};}},
  { id:"coalition",label:"Manage the governing coalition",cool:2,
    hint:"patronage, whips and promises — keeping your own benches loyal",
    gain:"your governing bloc +7, +2 Stability",
    cost:{gold:-12},requires:S=>!!S.pm,
    resolve:S=>{ const fx={}; fx[S.pm.bloc]=+7;
      return {cost:{gold:-12,stability:+2},fac:fx,chron:null,
      out:"Offices promised, feathers smoothed, one baronet bought outright. The benches hold — and the realm feels a steady hand."};}},
  { id:"public_works",label:"Commission public works",requires:S=>!!S.pm,
    hint:"roads, bridges, waterworks — the ministry builds what kings only decreed",
    cost:{gold:-24},fac:{provinces:+4,peasantry:+3},
    effect:S=>{S.development=clamp(S.development+7);},
    chron:S=>`the ministry raised works across ${S.nation} — bridges, roads, waterworks — and the country grew visibly richer.`,
    out:["Surveyors, then scaffolds, then traffic. Development rises where the ministry builds — and so does every future year's revenue."]},
  { id:"surplus",label:"Deliver a surplus budget",cool:3,requires:S=>!!S.pm&&netIncome(S)>0,
    hint:"prudent administration turned directly into gold and confidence",
    cost:{gold:+16,stability:+2},fac:{merchants:+3},
    chron:S=>`the ministry delivered a surplus, and the credit of ${S.nation} strengthened.`,
    out:["The books balance with room to spare. The funds notice; so do the lenders. Competence, it turns out, pays."]},
  { id:"early_election",label:"Call an early election",cool:4,
    hint:"go to the country — renew the mandate, or watch it pass to another interest",
    cost:{stability:-3},requires:S=>!!S.pm,
    effect:S=>{S.nextElection=S.turn+1;},
    chron:S=>`the ${S.pm.office} dissolved the chamber and went to the country.`,
    out:["Writs issued, hustings raised. The realm will speak at the next sitting."]},
];
const ACT_DOM={patronize:"faith",festival:"faith",festival_realm:"faith",
  fund_army:"martial",suppress:"martial",tour:"martial",
  trade:"fiscal",tax_decree:"fiscal",tax_request:"fiscal",privileges:"fiscal",surplus:"fiscal",
  appoint:"civil",address_commons:"civil",legislate:"civil",coalition:"civil",public_works:"civil",
  dissolve:"crown",refuse_ministry:"crown",early_election:"crown"};
const DOM_NAMES={martial:"The Sword",fiscal:"The Purse",faith:"The Altar",civil:"The Realm",crown:"The Prerogative"};
const DOM_ORDER=["crown","martial","fiscal","faith","civil"];
function actDomain(a){ return a.dom||ACT_DOM[a.id]||"civil"; }
function availableActions(S){ return ACTIONS.filter(a=>a.requires(S)&&!onCooldown(S,a.id)&&costMod(S,a.id)!==0); }
function onCooldown(S,id){ return (S.cooldowns[id]||0)>S.turn; }
function affordable(S,a){ const g=(adjCost(S,a).gold)||0; if(g>=0)return true; return (S.treasury+g)>=-OVERDRAFT; }
