/* =====================================================================
   EVENTS — recurrence-tiered pool
   freq: min turns between repeats (Infinity = once ever)
   ===================================================================== */
const EVENTS=[
  { id:"harvest",w:1.1,freq:3,title:"A Failed Harvest",
    text:S=>`A cold, wet season ruins the crop. Grain-carts are turned from the towns and the price of bread climbs by the week.`,
    choices:[
      {label:"Open the royal granaries",cost:{gold:-26,stability:+8},fac:{peasantry:+8,provinces:+4},
        chron:S=>`when the harvest failed, the Crown opened its granaries; the winter passed without revolt.`,
        out:"The queues are long but orderly, and no one who reaches them starves."},
      {label:"Let the grain-price find its level",cost:{gold:+6,stability:-13},fac:{merchants:+5,peasantry:-11,provinces:-5},
        chron:S=>`the Crown let bread run to its price through the famine; the merchants prospered and the poor remembered.`,
        out:"The merchants grow fat on scarcity. In two towns the crowds burn the granaries they could not afford."}]},
  { id:"border",w:1.0,freq:3,title:"A Neighbour Tests the Border",
    text:S=>`A rival crown's army is "on manoeuvre" a day's ride from your frontier. Their ambassador smiles and calls it nothing.`,
    choices:[
      {label:"March the army to meet them",cost:{gold:-12},
        resolve:S=>{ if(S.military>=45)return{cost:{arms:-2},fac:{officers:+6,provinces:+3},effect:S2=>{S2._celebrate={label:"the stand upon the frontier",turn:S2.turn+1};},chron:S=>`${S.nation} answered the provocation with steel, and the rival withdrew.`,out:"Your columns reach the river first and stand firm. Even a bloodless victory wears boots and horses — but strength shown once is seldom tested twice."};
          return{cost:{arms:-6,stability:-6},fac:{officers:-4,provinces:-5},chron:S=>`${S.nation} marched to a frontier it was too weak to hold, and lost border country for its pride.`,out:"Your thin regiments arrive late and outmatched. Three villages fly a foreign flag by autumn."};}},
      {label:"Buy them off with a discreet tribute",cost:{gold:-20,stability:+2},fac:{officers:-5,aristocracy:-3},
        chron:S=>`${S.nation} bought peace on its frontier with a quiet tribute.`,
        out:"A chest of gold changes hands in the dark. The border holds. The officers will not soon forgive."}]},
  { id:"noble_feud",w:1.0,freq:4,title:"Two Great Houses Draw Swords",
    text:S=>`A feud between two of the realm's proudest houses has spilled into blood. Both demand the Crown take their side.`,
    choices:[
      {label:"Rule firmly for one house",cost:{stability:+4},fac:{aristocracy:-3},
        chron:S=>`the Crown ruled sharply in the great feud; one proud house was raised as another was humbled.`,
        out:"You decide it, and mean it. One house bends the knee, grateful. The other files the grievance away."},
      {label:"Mediate a marriage between them",cost:{gold:-14},fac:{aristocracy:+7,clergy:+3},
        chron:S=>`the Crown ended the great feud with a wedding, binding two warring houses into one reluctant family.`,
        out:"A betrothal, a feast, a fragile peace — a dowry's price for the gratitude of both."},
      {label:"Let them exhaust each other",cost:{stability:-7},fac:{aristocracy:-6,peasantry:-3},
        chron:S=>`the Crown stood aside while two great houses bled each other white; both blamed the throne.`,
        out:"You do nothing, and the nobility learns the throne will not protect them. The lesson cuts both ways."}]},
  { id:"heresy",w:0.9,freq:4,title:"A Preacher Cries Against the Temple",
    text:S=>`A charismatic preacher draws huge crowds with a doctrine the hierarchs call heresy — and the poor call hope.`,
    choices:[
      {label:"Back the hierarchs and silence him",cost:{stability:-3},fac:{clergy:+9,peasantry:-6},
        chron:S=>`the Crown silenced the wandering preacher at the hierarchs' urging; orthodoxy held, and a martyr was quietly made.`,
        out:"The preacher is taken in the night. In the poor quarters, his words only travel faster."},
      {label:"Tolerate the new preaching",cost:{stability:+2},fac:{clergy:-9,peasantry:+7,merchants:+3},
        chron:S=>`the Crown let the new preaching stand; the common folk rejoiced and the hierarchs began counting the Crown's sins.`,
        out:"You let him preach. The crowds bless your tolerance. The hierarchs say nothing — which is itself an answer."}]},
  { id:"plague",w:0.8,freq:5,title:"A Fever in the Cities",
    text:S=>`A sickness moves through the crowded quarters faster than the physicians can name it. The dead are carried out by night.`,
    danger:true,
    choices:[
      {label:"Quarantine the cities and fund the physicians",cost:{gold:-26,stability:-3},fac:{peasantry:+6,clergy:+3},
        chron:S=>`${S.nation} met the fever with cordon and coin; trade stalled, but the graveyards filled slower than they might have.`,
        out:"The cities are sealed and the markets die for a season — but the toll is a fraction of what it could have been."},
      {label:"Keep the markets open — trade cannot stop",cost:{gold:+8,stability:-12},fac:{merchants:+5,peasantry:-9},courtRisk:true,
        chron:S=>`${S.nation} kept its markets open through the fever; the ledgers stayed whole and the parish registers did not.`,
        out:"Commerce keeps turning. So do the death-carts. The fever does not distinguish palace from hovel."}]},
  { id:"scandal",w:0.9,freq:5,title:"A Minister Is Revealed a Thief",
    text:S=>`A ledger surfaces: a trusted officer of the Crown has been diverting the state's gold into private estates for years.`,
    choices:[
      {label:"Arrest him publicly",cost:{gold:+10},fac:{peasantry:+6,merchants:+4,aristocracy:-3},
        chron:S=>`the Crown dragged its own thieving officer into the light; the coin recovered was modest, the lesson enormous.`,
        out:"He is marched from his townhouse in chains, in daylight. A cheap friendship to be seen ending."},
      {label:"Let him quietly resign abroad",cost:{gold:-4},fac:{aristocracy:+3,peasantry:-7,merchants:-4},
        chron:S=>`the Crown let its corrupt officer slip abroad with his fortune; the quiet was bought dear.`,
        out:"He is on a ship by dawn, gold and all. The sense that rules are for other people does not fade."}]},
  { id:"petition",w:1.0,freq:3,when:S=>rightsHeld(S).has("petition"),title:"The Commons Bring a Petition",
    text:S=>`The ${institutionWithRight(S,"petition")?institutionWithRight(S,"petition").name:"lower chamber"} arrives with a petition: relief from the harshest dues, and a hearing for the low-born.`,
    choices:[
      {label:"Grant the petition",cost:{gold:-16,stability:+6},fac:{peasantry:+9,merchants:+6,aristocracy:-4},grantPetition:true,
        chron:S=>`the Crown granted the Commons' petition; the low-born learned their voice could move the throne.`,
        out:"You hear them and act. Word runs through the wards: the chamber is not decoration. Their trust in it — and in you — deepens."},
      {label:"Receive it politely and shelve it",cost:{},fac:{peasantry:-6,merchants:-4},spurnPetition:true,
        chron:S=>`the Crown received the Commons' petition with courtesy and buried it; the courtesy fooled no one for long.`,
        out:"Warm words and a drawer that never opens. They notice. The chamber's patience is not infinite."}]},
  { id:"province_autonomy",w:0.9,freq:4,when:S=>S.facs.provinces.mood<58,title:"A Province Demands Home Rule",
    text:S=>`The far province of Marrow is tired of taxes decided in a capital it never sees. Its delegation asks for autonomy. The word behind the word is independence.`,
    choices:[
      {label:"Grant broad self-rule",cost:{gold:-10,stability:+7},fac:{provinces:+12,aristocracy:-3},
        chron:S=>`the Crown answered Marrow with a generous grant of self-rule; the province stayed, proudly, within the realm.`,
        out:"The delegation leaves with more than they dared ask. Marrow stays — loudly — inside your borders."},
      {label:"Refuse and garrison the province",cost:{gold:-12,stability:+4},fac:{provinces:-12,peasantry:-4,officers:+3},
        chron:S=>`the Crown answered Marrow with the regiment rather than the pen; its loyalty was never again freely given.`,
        out:"The garrisons march in. Marrow goes quiet — the quiet of a held breath."}]},
  { id:"windfall",w:0.6,freq:Infinity,title:"Silver in the Eastern Hills",
    text:S=>`Surveyors return wild-eyed: a seam of silver in the eastern hills, richer than any in living memory.`,
    choices:[
      {label:"Claim the seam for the Crown",cost:{gold:+44,stability:-4},fac:{merchants:-3,provinces:-3},
        chron:S=>`the Crown claimed the silver hills entire; the treasury overflowed, and the slow sickness of easy money set in.`,
        out:"Gold pours into the vaults. Within a year your court has half-forgotten how to balance a book."},
      {label:"Auction claims to the merchants",cost:{gold:+20},fac:{merchants:+9},
        chron:S=>`the Crown sold its silver hills to the highest bidders; the throne took a steady cut.`,
        out:"The auction is frantic. The treasury gets a healthy slice; a dozen houses get dangerously rich."},
      {label:"Endow the realm's development",cost:{gold:+8},fac:{merchants:+4,peasantry:+4},effect:S=>{S.development=clamp(S.development+10);},
        chron:S=>`the Crown spent its silver on the realm itself — roads, mills, harbours — and the country was richer for a century.`,
        out:"You bank the flood into the realm's bones. The immediate gain is modest. The compounding one is not."}]},
  { id:"officer_grumble",w:0.9,freq:4,when:S=>S.facs.officers.mood<46,title:"The Officers Grumble",
    text:S=>`Pay is late and promotions have gone to court favourites over battlefield men. Muttering officers are how thrones fall.`,
    choices:[
      {label:"Pay arrears and reward the veterans",cost:{gold:-24},fac:{officers:+12},
        chron:S=>`the Crown paid its soldiers what it owed; the muttering in the barracks stilled.`,
        out:"Back-pay, medals, promotions by merit. The corps remembers it serves a sovereign, not a forgetful paymaster."},
      {label:"Remind them who commands",cost:{stability:+3},fac:{officers:-9},
        chron:S=>`the Crown answered the officers' grievance with a cold reminder of rank; obedience was had, affection was not.`,
        out:"You pull rank, hard. They salute. Something that was loyalty curdles into mere discipline."}]},
  { id:"beggars",w:0.7,freq:4,when:S=>S.facs.peasantry.mood<46,title:"The Poor at the Palace Gate",
    text:S=>`Hunger has driven the rural poor to the capital in their thousands. They are camped at the gate, silent, waiting.`,
    choices:[
      {label:"Feed them from the royal table",cost:{gold:-18,stability:+5},fac:{peasantry:+10,clergy:+4},
        chron:S=>`the Crown fed the starving from its own stores, and the gesture was sung of long after the hunger passed.`,
        out:"The kitchens work day and night. A fortune in bread — worth every loaf in loyalty."},
      {label:"Have the guard move them on",cost:{stability:+6},fac:{peasantry:-12,clergy:-4},
        chron:S=>`the Crown had its guard clear the starving from the gate; a wound was opened that did not close.`,
        out:"The gate is clear. The memory is not."}]},
  { id:"chamber_hunger",w:0.9,freq:5,when:S=>!S.pm&&S.gov.institutions.length>0&&S.gov.institutions[0].power<30,
    title:S=>`The ${S.gov.institutions[0].name} Demands More`,
    text:S=>`A chamber, once summoned, does not stay grateful. The ${S.gov.institutions[0].name} has drawn up a formal address: it holds too little power for the burdens laid upon it, and it wants more. The address is polite. The mood behind it is not.`,
    choices:[
      {label:"Grant a further measure of power",cost:{stability:+3},fac:{aristocracy:+5,clergy:+2},
        effect:S=>{transferPower(S,S.gov.institutions[0],8);},
        chron:S=>`the ${S.gov.institutions[0].name} pressed for a greater share of power, and the Crown yielded a measure gracefully.`,
        out:"You grant it before it must be taken. The chamber notes — approvingly — which kind of crown it serves."},
      {label:"Refuse the address",cost:{stability:-4},fac:{aristocracy:-6,clergy:-4},
        chron:S=>`the Crown refused the chamber's address for greater power; the refusal was filed, and remembered.`,
        out:"Refused with full ceremony. The address goes into the chamber's records — the kind of document that gets re-read in worse years."}]},
  { id:"commons_cry",w:0.8,freq:6,when:S=>S.gov.institutions.length>0&&!S.gov.institutions.some(i=>i.composition!=="nobility")&&(S.facs.merchants.strength+S.facs.peasantry.strength)>=95,
    title:"The Cry for a Commons",
    text:S=>`The realm below the great houses has grown too big to ignore: guild money, market towns, a countryside that reads. Petitions arrive from forty towns with one demand — a chamber of their own.`,
    choices:[
      {label:"Receive the petitioners warmly",cost:{stability:+4},fac:{merchants:+4,peasantry:+4,aristocracy:-3},
        chron:S=>`the Crown received the towns' great petition for a commons with warmth, and the question was opened that would not again close.`,
        out:"You make no promise — but you let them be heard, at length, in public. The reform now has a constituency. (Seat a lower chamber when you're ready.)"},
      {label:"Dismiss it — the estates speak for the realm",cost:{stability:-5},fac:{merchants:-6,peasantry:-7},
        chron:S=>`the Crown dismissed the cry for a commons; the towns went home and began keeping their own counsel.`,
        out:"The petitioners are sent home with courtesies. What they build next will not be a petition."}]},
  { id:"restoration",w:0.8,freq:6,when:S=>!!S.pm&&S.gov.crown.power>=40&&S.gov.crown.power<50,title:"The Crown Demands Restoration",
    text:S=>`${styled(S,S.monarch)} has had enough of ministers. With the officers listening and the old families nodding, the palace formally demands its powers returned. This is the strongest a crown can be while you still govern — and it knows it.`,
    choices:[
      {label:"Concede a measure of power back",cost:{stability:+5},fac:{aristocracy:+6},
        effect:S=>{powerToCrown(S,S.gov.institutions[0],8);},
        chron:S=>`the ministry conceded powers back to the Crown, and the arrow of history bent, briefly, the other way.`,
        out:"You hand a slice of the prerogative back. The palace glows; the chamber grumbles; the storm passes — this time."},
      {label:"Refuse — and dare the palace to act",
        resolve:S=>{ if(S.military>=45&&S.facs.officers.mood>=48){
            return {cost:{stability:-8},effect:S2=>{S2.gov.crown.power=Math.min(S2.gov.crown.power,20);const diff=100-(S2.gov.crown.power+S2.gov.institutions.reduce((a,i)=>a+i.power,0));if(diff>0)S2.gov.institutions[0].power+=diff;},fac:{officers:+5,aristocracy:-8},
              chron:S2=>`the Crown moved against its ministry and the army did not follow; the attempted restoration broke the throne down to a figurehead.`,
              out:"The palace plays its hand — and the regiments stay in their barracks, awaiting YOUR orders. The restoration collapses in a week. The Crown will never be this strong again."};}
          return {cost:{stability:-14,arms:-8},effect:S2=>{powerToCrown(S2,S2.gov.institutions[0],22);},fac:{officers:-6,aristocracy:+8},
            chron:S2=>`the Crown moved against its ministry with the officers at its back, and won; power flowed back to the palace at bayonet-point.`,
            out:"The palace plays its hand — and the officers choose the Crown. Soldiers in the lobby, the mace carried out. You keep the office; the office keeps much less."};}},
      {label:"Buy the palace's patience",cost:{gold:-30},fac:{aristocracy:+4},
        chron:S=>`the ministry bought the Crown's patience with a settlement of revenues and honours.`,
        out:"A civil list, some honours, a yacht. Undignified, affordable, effective."}]},
  { id:"abdication_cry",w:0.9,freq:6,when:S=>!S.pm&&legitimacy(S)<25&&!!heirOf(S)&&!S.regency,title:"The Cry for Abdication",
    text:S=>`The realm has stopped pretending. In the chambers, the taverns and the great houses alike, one word travels: abdicate. ${heirOf(S).name} waits, carefully saying nothing.`,
    choices:[
      {label:"Lay down the crown in favour of the heir",cost:{stability:+8},
        effect:S=>{S._abdicate=true;},
        chron:S=>`${styled(S,S.monarch)}, unloved and unlamented, laid down the crown in favour of the heir.`,
        out:"The instrument is signed without ceremony. By year's end the crown sits on a fresher head — and the realm exhales."},
      {label:"Refuse — the crown is not the mob's to demand",cost:{stability:-6},
        effect:S=>{S.legitPen=(S.legitPen||0)+4;},
        chron:S=>`the Crown refused the realm's demand for abdication, and wore its unpopularity like armour.`,
        out:"You stay. The word doesn't stop travelling."}]},
  { id:"crown_meddles",w:0.9,freq:4,when:S=>!!S.pm&&S.gov.crown.power>=22,title:"The Crown Meddles",
    text:S=>`${styled(S,S.monarch)} has taken up a pet cause and presses the ministry to fund it — publicly enough that refusal will be noticed.`,
    choices:[
      {label:"Indulge the sovereign",cost:{gold:-12},fac:{aristocracy:+4},
        chron:S=>`the ministry indulged the Crown's enthusiasm, and palace and cabinet kept their peace.`,
        out:"The scheme is funded, the sovereign delighted, the constitutional question left politely unasked."},
      {label:"Decline — the ministry sets policy now",cost:{stability:-3},fac:{aristocracy:-3},
        chron:S=>`the ministry declined the Crown's request, and the palace learned where policy was now made.`,
        out:"A frosty audience. The refusal stands — and so, a little more clearly, does the new order of things."}]},
  { id:"foreign_match",w:0.7,freq:5,title:"A Foreign Crown Proposes Alliance",
    text:S=>`An envoy from a powerful neighbour proposes a binding alliance — sealed, as such things are, by marriage and obligation.`,
    choices:[
      {label:"Accept the alliance",cost:{arms:+6},fac:{aristocracy:+3,officers:+3},
        chron:S=>`${S.nation} bound itself to a powerful neighbour; the alliance outlasted the affection, as alliances do.`,
        out:"Vows exchanged with great pomp. You have a friend — and its enemies."},
      {label:"Decline and keep your hands free",cost:{stability:+2},fac:{merchants:+2},
        chron:S=>`${S.nation} declined the offered alliance and kept its independence unencumbered.`,
        out:"Refused with every courtesy. You owe no one, and no one owes you."}]},
];
function eligibleEvents(S){
  return EVENTS.filter(e=>{
    if(e.when&&!e.when(S))return false;
    const last=S.eventLast[e.id];
    if(last!=null){ if(e.freq===Infinity)return false; if(S.turn-last<e.freq)return false; }
    return true;
  });
}
