"use strict";
/* =====================================================================
   EVENTS — recurrence-tiered pool
   freq: min turns between repeats (Infinity = once ever)
   ===================================================================== */
const EVENTS=[
  { id:"harvest",w:1.1,freq:3,title:"A Failed Harvest",
    text:S=>`A cold, wet season ruins the crop. Grain-carts are turned from the towns and the price of bread climbs by the week.`,
    choices:[
      {label:"Open the royal granaries",cost:{gold:-26,stability:+8},fac:{peasantry:+8,provinces:+4},
        chron:S=>`when the harvest failed, the Crown opened its granaries; the winter passed without revolt.`,
        out:"The queues are long but orderly, and no one who reaches them starves."},
      {label:"Let the grain-price find its level",cost:{gold:+6,stability:-13},fac:{merchants:+5,peasantry:-11,provinces:-5},
        chron:S=>`the Crown let bread run to its price through the famine; the merchants prospered and the poor remembered.`,
        out:"The merchants grow fat on scarcity. In two towns the crowds burn the granaries they could not afford."}]},
  { id:"border",w:1.0,freq:3,title:"A Neighbour Tests the Border",
    text:S=>`A rival crown's army is "on manoeuvre" a day's ride from your frontier. Their ambassador smiles and calls it nothing.`,
    choices:[
      {label:"March the army to meet them",cost:{gold:-12},
        resolve:S=>{ if(S.military>=45)return{cost:{arms:-2},fac:{officers:+6,provinces:+3},effect:S2=>{S2._celebrate={label:"the stand upon the frontier",turn:S2.turn+1};},chron:S=>`${S.nation} answered the provocation with steel, and the rival withdrew.`,out:"Your columns reach the river first and stand firm. Even a bloodless victory wears boots and horses — but strength shown once is seldom tested twice."};
          return{cost:{arms:-6,stability:-6},fac:{officers:-4,provinces:-5},chron:S=>`${S.nation} marched to a frontier it was too weak to hold, and lost border country for its pride.`,out:"Your thin regiments arrive late and outmatched. Three villages fly a foreign flag by autumn."};}},
      {label:"Buy them off with a discreet tribute",cost:{gold:-20,stability:+2},fac:{officers:-5,aristocracy:-3},
        chron:S=>`${S.nation} bought peace on its frontier with a quiet tribute.`,
        out:"A chest of gold changes hands in the dark. The border holds. The officers will not soon forgive."}]},
  { id:"noble_feud",w:1.0,freq:4,when:S=>eraIdx(S)<=3&&S.facs.aristocracy.strength>=25,title:"Two Great Houses Draw Swords",
    text:S=>`A feud between two of the realm's proudest houses has spilled into blood. Both demand the Crown take their side.`,
    choices:[
      {label:"Rule firmly for one house",cost:{stability:+4},fac:{aristocracy:-3},
        chron:S=>`the Crown ruled sharply in the great feud; one proud house was raised as another was humbled.`,
        out:"You decide it, and mean it. One house bends the knee, grateful. The other files the grievance away."},
      {label:"Mediate a marriage between them",cost:{gold:-14},fac:{aristocracy:+7,clergy:+3},
        chron:S=>`the Crown ended the great feud with a wedding, binding two warring houses into one reluctant family.`,
        out:"A betrothal, a feast, a fragile peace — a dowry's price for the gratitude of both."},
      {label:"Let them exhaust each other",cost:{stability:-7},fac:{aristocracy:-6,peasantry:-3},
        chron:S=>`the Crown stood aside while two great houses bled each other white; both blamed the throne.`,
        out:"You do nothing, and the nobility learns the throne will not protect them. The lesson cuts both ways."}]},
  { id:"heresy",w:0.9,freq:4,title:"A Preacher Cries Against the Temple",
    text:S=>`A charismatic preacher draws huge crowds with a doctrine the hierarchs call heresy — and the poor call hope.`,
    choices:[
      {label:"Back the hierarchs and silence him",cost:{stability:-3},fac:{clergy:+9,peasantry:-6},
        chron:S=>`the Crown silenced the wandering preacher at the hierarchs' urging; orthodoxy held, and a martyr was quietly made.`,
        out:"The preacher is taken in the night. In the poor quarters, his words only travel faster."},
      {label:"Tolerate the new preaching",cost:{stability:+2},fac:{clergy:-9,peasantry:+7,merchants:+3},
        chron:S=>`the Crown let the new preaching stand; the common folk rejoiced and the hierarchs began counting the Crown's sins.`,
        out:"You let him preach. The crowds bless your tolerance. The hierarchs say nothing — which is itself an answer."}]},
  { id:"plague",w:0.8,freq:5,title:"A Fever in the Cities",
    text:S=>`A sickness moves through the crowded quarters faster than the physicians can name it. The dead are carried out by night.`,
    danger:true,
    choices:[
      {label:"Quarantine the cities and fund the physicians",cost:{gold:-26,stability:-3},fac:{peasantry:+6,clergy:+3},
        chron:S=>`${S.nation} met the fever with cordon and coin; trade stalled, but the graveyards filled slower than they might have.`,
        out:"The cities are sealed and the markets die for a season — but the toll is a fraction of what it could have been."},
      {label:"Keep the markets open — trade cannot stop",cost:{gold:+8,stability:-12},fac:{merchants:+5,peasantry:-9},courtRisk:true,
        chron:S=>`${S.nation} kept its markets open through the fever; the ledgers stayed whole and the parish registers did not.`,
        out:"Commerce keeps turning. So do the death-carts. The fever does not distinguish palace from hovel."}]},
  { id:"scandal",w:0.9,freq:5,title:"A Minister Is Revealed a Thief",
    text:S=>`A ledger surfaces: a trusted officer of the Crown has been diverting the state's gold into private estates for years.`,
    choices:[
      {label:"Arrest him publicly",cost:{gold:+10},fac:{peasantry:+6,merchants:+4,aristocracy:-3},
        chron:S=>`the Crown dragged its own thieving officer into the light; the coin recovered was modest, the lesson enormous.`,
        out:"He is marched from his townhouse in chains, in daylight. A cheap friendship to be seen ending."},
      {label:"Let him quietly resign abroad",cost:{gold:-4},fac:{aristocracy:+3,peasantry:-7,merchants:-4},
        chron:S=>`the Crown let its corrupt officer slip abroad with his fortune; the quiet was bought dear.`,
        out:"He is on a ship by dawn, gold and all. The sense that rules are for other people does not fade."}]},
  { id:"petition",w:1.0,freq:3,when:S=>rightsHeld(S).has("petition"),title:"The Commons Bring a Petition",
    text:S=>`The ${institutionWithRight(S,"petition")?institutionWithRight(S,"petition").name:"lower chamber"} arrives with a petition: relief from the harshest dues, and a hearing for the low-born.`,
    choices:[
      {label:"Grant the petition",cost:{gold:-16,stability:+6},fac:{peasantry:+9,merchants:+6,aristocracy:-4},grantPetition:true,
        chron:S=>`the Crown granted the Commons' petition; the low-born learned their voice could move the throne.`,
        out:"You hear them and act. Word runs through the wards: the chamber is not decoration. Their trust in it — and in you — deepens."},
      {label:"Receive it politely and shelve it",cost:{},fac:{peasantry:-6,merchants:-4},spurnPetition:true,
        chron:S=>`the Crown received the Commons' petition with courtesy and buried it; the courtesy fooled no one for long.`,
        out:"Warm words and a drawer that never opens. They notice. The chamber's patience is not infinite."}]},
  { id:"province_autonomy",w:0.9,freq:4,when:S=>provinces(S).some(p=>!p.core&&!p.autonomy),
    title:S=>{const p=autonomySeeker(S);return `${p?p.name:"A Province"} Demands Home Rule`;},
    text:S=>{const p=autonomySeeker(S);
      return `${p?p.name:"The far country"} is tired of taxes decided in a capital it never sees${p?`, and its delegation has come up from ${p.seat} to say so`:""}. They ask for autonomy. The word behind the word is independence.`;},
    choices:[
      {label:"Grant broad self-rule",cost:{gold:-10,stability:+7},fac:{provinces:+12,aristocracy:-3},
        effect:S=>{const p=autonomySeeker(S);if(p){p.autonomy=true;p.loyalty=clamp(p.loyalty+18);}},
        chron:S=>`the Crown answered the demand with a generous grant of self-rule; the province stayed, proudly, within the realm.`,
        out:S=>{const p=autonomySeeker(S);return `The delegation leaves with more than they dared ask. ${p?p.name:"The province"} stays — loudly — inside your borders.`;}},
      {label:"Refuse and garrison the province",cost:{gold:-12,stability:+4},fac:{provinces:-12,peasantry:-4,officers:+3},
        effect:S=>{leanOnArmy(S,2);const p=autonomySeeker(S);if(p){p.loyalty=clamp(p.loyalty-16);p.garrisoned=true;}},
        chron:S=>{const p=autonomySeeker(S);return `${crownWord(S)} answered ${p?p.name:"the province"} with the regiment rather than the pen; its loyalty was never again freely given.`;},
        out:S=>{const p=autonomySeeker(S);return `The garrisons march in. ${p?p.name:"The province"} goes quiet — the quiet of a held breath.`;}}]},
  { id:"windfall",w:0.6,freq:Infinity,title:"Silver in the Eastern Hills",
    text:S=>`Surveyors return wild-eyed: a seam of silver in the eastern hills, richer than any in living memory.`,
    choices:[
      {label:"Claim the seam for the Crown",cost:{gold:+44,stability:-4},fac:{merchants:-3,provinces:-3},
        chron:S=>`the Crown claimed the silver hills entire; the treasury overflowed, and the slow sickness of easy money set in.`,
        out:"Gold pours into the vaults. Within a year your court has half-forgotten how to balance a book."},
      {label:"Auction claims to the merchants",cost:{gold:+20},fac:{merchants:+9},
        chron:S=>`the Crown sold its silver hills to the highest bidders; the throne took a steady cut.`,
        out:"The auction is frantic. The treasury gets a healthy slice; a dozen houses get dangerously rich."},
      {label:"Endow the realm's development",cost:{gold:+8},fac:{merchants:+4,peasantry:+4},effect:S=>{raiseDevelopment(S,10);},
        chron:S=>`the Crown spent its silver on the realm itself — roads, mills, harbours — and the country was richer for a century.`,
        out:"You bank the flood into the realm's bones. The immediate gain is modest. The compounding one is not."}]},
  { id:"officer_grumble",w:0.9,freq:4,when:S=>S.facs.officers.mood<46,title:"The Officers Grumble",
    text:S=>`Pay is late and promotions have gone to court favourites over battlefield men. Muttering officers are how thrones fall.`,
    choices:[
      {label:"Pay arrears and reward the veterans",cost:{gold:-24},fac:{officers:+12},
        chron:S=>`the Crown paid its soldiers what it owed; the muttering in the barracks stilled.`,
        out:"Back-pay, medals, promotions by merit. The corps remembers it serves a sovereign, not a forgetful paymaster."},
      {label:"Remind them who commands",cost:{stability:+3},fac:{officers:-9},
        chron:S=>`the Crown answered the officers' grievance with a cold reminder of rank; obedience was had, affection was not.`,
        out:"You pull rank, hard. They salute. Something that was loyalty curdles into mere discipline."}]},
  { id:"beggars",w:0.7,freq:4,when:S=>S.facs.peasantry.mood<46,title:"The Poor at the Palace Gate",
    text:S=>`Hunger has driven the rural poor to the capital in their thousands. They are camped at the gate, silent, waiting.`,
    choices:[
      {label:"Feed them from the royal table",cost:{gold:-18,stability:+5},fac:{peasantry:+10,clergy:+4},
        chron:S=>`the Crown fed the starving from its own stores, and the gesture was sung of long after the hunger passed.`,
        out:"The kitchens work day and night. A fortune in bread — worth every loaf in loyalty."},
      {label:"Have the guard move them on",cost:{stability:+6},fac:{peasantry:-12,clergy:-4},
        effect:S=>{leanOnArmy(S,1);},
        chron:S=>`the Crown had its guard clear the starving from the gate; a wound was opened that did not close.`,
        out:"The gate is clear. The memory is not."}]},
  /* ================= DISASTERS & AGE-SPECIFIC TROUBLES =================
     Each is gated to the ages where it belongs, and each is capable of
     hurting. A realm that ignores them should feel it for decades.      */
  { id:"murrain",w:1.1,freq:5,when:S=>eraIdx(S)<=1,title:"The Great Murrain",
    text:S=>`A sickness is in the cattle. It began in one valley and it is now in nine; the beasts swell, stagger and die, and the ploughs stand idle behind them. The countryside is looking at the harvest it will not have.`,
    choices:[
      {label:"Open the granaries and remit the year's dues",cost:{gold:-26,stability:+3},fac:{peasantry:+9,provinces:+6,aristocracy:-4},
        chron:S=>`a murrain swept the herds of ${S.nation}; the Crown opened its granaries and forgave the year's dues.`,
        out:"Grain carts on every road and a year's rents written off. It is ruinously expensive and it is remembered for two generations."},
      {label:"Let the country bear it",cost:{stability:-13},fac:{peasantry:-14,provinces:-9},
        effect:S=>{lowerDevelopment(S,6);},
        chron:S=>`a murrain swept the herds and the Crown did nothing; villages emptied and the land went out of tillage.`,
        out:"The herds die, then the villages thin, then the fields go back to scrub. Development falls and will take decades to recover."},
      {label:"Order the herds culled and the roads closed",cost:{gold:-14,stability:-6},fac:{peasantry:-7,merchants:-6},
        effect:S=>{lowerDevelopment(S,2);},
        chron:S=>`the Crown ordered the herds culled and the roads shut, and the murrain burned itself out early.`,
        out:"Brutal, unpopular, and effective. The sickness dies out in a season — along with a good deal of somebody's livelihood."}]},
  { id:"harvest_fail",w:1.2,freq:4,title:"The Harvest Fails",
    text:S=>`Rain when there should have been sun, and then none at all. The granaries will not fill this year, and the price of bread has already told everyone what that means before the survey has even been read.`,
    choices:[
      {label:"Buy grain abroad at whatever it costs",cost:{gold:-30,stability:+4},fac:{peasantry:+8,merchants:+3},
        chron:S=>`a failed harvest was met by grain bought abroad at ruinous cost.`,
        out:"Ships and wagons and a bill that will be felt for years. Nobody starves, which is the whole point."},
      {label:"Fix the price of bread by decree",cost:{stability:-4},fac:{peasantry:+6,merchants:-11},
        chron:S=>`the Crown fixed the price of bread against a failed harvest; the merchants took the loss and remembered it.`,
        out:"Bread stays affordable and the grain factors are furious. Some of it quietly leaves the country instead."},
      {label:"Let the market find its level",cost:{stability:-12},fac:{peasantry:-15,merchants:+7,provinces:-6},
        chron:S=>`the Crown let bread find its own price through a hungry winter.`,
        out:"The price triples. The factors do very well. There is a word for what happens in the towns by spring, and it is not 'discontent'."}]},
  { id:"pestilence",w:0.9,freq:7,title:"Pestilence",
    text:S=>`It arrives the way it always does — a port, a rumour, then a street where nobody answers the door. The physicians disagree about everything except that it is spreading.`,
    choices:[
      {label:"Quarantine the ports and the afflicted towns",cost:{gold:-20,stability:-5},fac:{merchants:-9,clergy:+4},
        effect:S=>{S._plagueMild=true;},
        chron:S=>`pestilence came to ${S.nation} and was met with quarantine; trade suffered and the death rolls stayed short.`,
        out:"Chains across the harbour and cordons around three towns. Trade strangles for a year. Far fewer graves than there might have been."},
      {label:"Trust to prayer and processions",cost:{stability:-9},fac:{clergy:+9,peasantry:-6},
        effect:S=>{lowerDevelopment(S,7);S.family.forEach(p=>{if(p.alive&&chance(0.12)){p.alive=false;p.diedTurn=S.turn;S.notices.push({t:"d",id:p.id,name:p.name,age:p.age});}});},
        chron:S=>`pestilence swept the realm and was answered with processions; it took the poor, the rich, and some of the royal house.`,
        out:"The processions are magnificent and they gather the whole city into one place, which is exactly the difficulty. The rolls are long. The palace is not spared."},
      {label:"Pay the physicians and open the pest-houses",cost:{gold:-26},fac:{peasantry:+6,clergy:-5},
        effect:S=>{lowerDevelopment(S,2);},
        chron:S=>`the Crown paid for physicians and pest-houses through the plague year.`,
        out:"Expensive, half-effective, and resented from the pulpits for meddling with providence. Fewer die than would have."}]},
  { id:"mutiny",w:1.1,freq:5,when:S=>eraIdx(S)>=2&&(S._armyUpkeep||0)>0,title:"The Regiments Are Unpaid",
    text:S=>`A standing army is a wonderful thing until the pay chest is late. Three regiments have not been paid in eleven months. They have not deserted — which, the officers explain carefully, is not the same as being reliable.`,
    choices:[
      {label:"Pay the arrears in full, at once",cost:{gold:-34,stability:+4},fac:{officers:+11},
        chron:S=>`the Crown found the money and paid the army's arrears in full.`,
        out:"The chests go out under guard and the mood turns within a week. Soldiers who are paid on time are a different animal entirely."},
      {label:"Pay half and promise the rest",cost:{gold:-16,stability:-5},fac:{officers:-6},
        chron:S=>`the Crown paid half the army's arrears and promised the remainder.`,
        out:"Half now buys you a year. The officers write it down. Everyone writes it down."},
      {label:"Let them plunder the country instead",cost:{stability:-16},fac:{officers:+5,peasantry:-16,provinces:-13},
        effect:S=>{lowerDevelopment(S,5);},
        chron:S=>`unpaid regiments were turned loose upon the countryside in lieu of wages.`,
        out:"You solve an army problem by creating a country problem. The regiments are content. Four districts are not, and will not be for a long time."}]},
  { id:"siege_ledger",w:1.0,freq:6,when:S=>eraIdx(S)>=2&&ownsAdv(S,"bastion"),title:"The Fortress Ledger",
    text:S=>`The engineers present their accounts. The bastions are magnificent, unbreachable, and consuming more of the revenue than the entire civil government. They would like to discuss the next phase.`,
    choices:[
      {label:"Build on — the realm must be unassailable",cost:{gold:-30},fac:{officers:+7,merchants:-7},
        effect:S=>{S.military=clamp(S.military+7);S._armyUpkeep=(S._armyUpkeep||0)+4;},
        chron:S=>`the Crown pressed on with the fortress programme whatever the cost.`,
        out:"Unassailable, and closer to insolvent every year. This is precisely how real crowns ended up begging their estates for money."},
      {label:"Halt the programme where it stands",cost:{stability:-5},fac:{officers:-9,merchants:+6},
        effect:S=>{S._armyUpkeep=Math.max(0,(S._armyUpkeep||0)-5);},
        chron:S=>`the Crown halted the fortress programme, half-finished, to save the treasury.`,
        out:"Half a ring of works and a saved treasury. The engineers are appalled; the bankers are relieved."}]},
  { id:"bank_run",w:1.0,freq:6,when:S=>eraIdx(S)>=3&&(S._creditBonus||0)>0,title:"The Banks Will Not Lend",
    text:S=>`A rumour, a refused bill, a queue outside a counting house at dawn. By the third day the credit of the realm is a question rather than an assumption, and the Crown's own paper is trading below its face.`,
    choices:[
      {label:"Guarantee the banks from the treasury",cost:{gold:-32,stability:+3},fac:{merchants:+11},
        chron:S=>`the Crown guaranteed the banks through the panic and the credit of ${S.nation} held.`,
        out:"You spend a fortune to stop a queue. It works, and nobody thanks you, because the disaster that didn't happen is invisible."},
      {label:"Let the weak houses fail",cost:{stability:-11},fac:{merchants:-14,peasantry:-5},
        effect:S=>{S._creditBonus=Math.max(0,(S._creditBonus||0)-50);lowerDevelopment(S,4);},
        chron:S=>`the Crown let the banking houses fail; credit contracted and did not return for a generation.`,
        out:"Three houses go down and take a great deal of other people's money with them. Your own borrowing costs more from now on."}]},
  { id:"bread_riots",w:1.1,freq:5,when:S=>eraIdx(S)>=3&&(S.facs.peasantry.mood<45||S.facs.merchants.mood<40),title:"Bread Riots in the Capital",
    text:S=>`It starts at a bakery and by evening it is four streets. They are not asking for a chamber or a charter. They are asking for bread, which is a far harder demand to negotiate away.`,
    choices:[
      {label:"Send the troops in",cost:{stability:-8},fac:{peasantry:-16,officers:+4,merchants:+5},
        effect:S=>{S.legitPen=(S.legitPen||0)+6;},
        chron:S=>`bread riots in the capital were put down by musketry.`,
        out:"Order is restored by evening. There is a number attached to that, and the newspapers — or the pamphlets, or the balladeers — will make sure it is remembered."},
      {label:"Open the crown's own stores",cost:{gold:-24,stability:+5},fac:{peasantry:+11},
        chron:S=>`the Crown opened its own stores to the rioting poor, and the streets emptied peacefully.`,
        out:"Carts of grain instead of volleys. It costs a great deal and it buys something no volley ever has."},
      {label:"Hang the ringleaders and fix the price",cost:{stability:-3},fac:{peasantry:-6,merchants:-8},
        chron:S=>`the ringleaders were hanged and the price of bread fixed by proclamation.`,
        out:"Both barrels: a gallows and a price control. The streets clear. Nobody is happy, which is at least even-handed."}]},
  { id:"pamphlet_war",w:1.1,freq:4,when:S=>eraIdx(S)>=4||ownsAdv(S,"press"),title:"The Pamphlet War",
    text:S=>`Somebody with a press and no fear has begun printing about the court. It is funny, it is filthy, it is largely accurate, and it is being read aloud in every coffee house in the capital.`,
    choices:[
      {label:"Find the press and break it",cost:{gold:-8,stability:-6},fac:{clergy:+5,merchants:-8,reformers:-9},
        effect:S=>{S.legitPen=(S.legitPen||0)+5;},
        chron:S=>`the Crown hunted down the presses; the pamphlets multiplied in the hunting.`,
        out:"You break one press. Four more appear, and now the story is about the breaking rather than the scandal."},
      {label:"Answer it — buy presses of your own",cost:{gold:-18},fac:{merchants:+4},
        effect:S=>{S._know.press=(S._know.press||0)+0.3;},
        chron:S=>`the Crown answered the pamphleteers in print rather than by arrest.`,
        out:"Undignified, effective, and quietly the beginning of something: the realm now has a government that argues in public."},
      {label:"Ignore it entirely",cost:{stability:-3},fac:{reformers:+4},
        chron:S=>`the Crown ignored the pamphleteers, and the pamphlets went on.`,
        out:"It burns for a season and moves on to somebody else. Some of what was printed sticks anyway."}]},
  { id:"salon_plot",w:0.9,freq:6,when:S=>eraIdx(S)>=4,title:"The Conspiracy of the Salons",
    text:S=>`It is not a plot exactly. It is a dozen well-born people who meet to discuss philosophy, and who have lately been discussing which philosophies a crown could survive. One of them has written it down.`,
    choices:[
      {label:"Arrest them",cost:{stability:-7},fac:{aristocracy:-9,reformers:-11,clergy:+6},
        effect:S=>{S.legitPen=(S.legitPen||0)+7;},
        chron:S=>`the salon philosophers were arrested, and became the most widely read men in the realm.`,
        out:"They go to prison, where they write. What they write travels further than their conversation ever did."},
      {label:"Invite them to court instead",cost:{gold:-14,stability:+4},fac:{aristocracy:+5,reformers:+9,clergy:-6},
        effect:S=>{S._advDiscount=(S._advDiscount||1)*0.96;},
        chron:S=>`the Crown brought the philosophers to court and made patronage of what might have been sedition.`,
        out:"Pensions, dinners and flattery. Two of them become sincere royalists. The rest at least write more carefully."},
      {label:"Have them watched and left alone",fac:{reformers:+3},
        chron:S=>`the Crown had the salons watched, and did nothing further.`,
        out:"A drawer fills with reports that nobody acts on. It is the cheapest option and it decides nothing."}]},
  { id:"great_fire",w:0.85,freq:8,title:"The Capital Burns",
    text:S=>`It began in a workshop and the wind was wrong. By the second night a quarter of the capital is gone and the river is full of people who saved nothing.`,
    choices:[
      {label:"Rebuild in stone at the crown's charge",cost:{gold:-36,stability:+6},fac:{merchants:+8,peasantry:+7,provinces:-3},
        effect:S=>{raiseDevelopment(S,5);},
        chron:S=>`after the great fire the Crown rebuilt the capital in stone at its own charge.`,
        out:"A colossal bill and a better city — wider streets, stone frontages, and a reputation that outlives everyone involved."},
      {label:"Leave the rebuilding to those who own the ground",cost:{stability:-9},fac:{merchants:-6,peasantry:-9},
        effect:S=>{lowerDevelopment(S,5);},
        chron:S=>`the burnt capital was left to rebuild itself, and did so badly.`,
        out:"It goes back up crooked, wooden and fast, which means it will burn again. The displaced are still displaced a decade later."}]},
  /* ================= RUPTURE: PROVINCIAL SECESSION ================= */
  { id:"prov_warning",w:1.4,freq:3,when:S=>restiveProvinces(S).length>0,
    title:S=>`Trouble in ${restiveProvinces(S)[0].name}`,
    text:S=>{const p=restiveProvinces(S)[0];
      return `The assizes at ${p.seat} returned empty again. The crown's writ is read aloud in ${p.name} and then, politely, ignored; the tax farmers travel with escorts or not at all. Loyalty there stands at ${Math.round(p.loyalty)}, and the word being used in the market is not 'grievance'.`;},
    choices:[
      {label:"Send a royal to govern them in person",cost:{gold:-16},fac:{provinces:+6},
        effect:S=>{const p=restiveProvinces(S)[0]; if(!p)return;
          const cand=(S.family||[]).filter(x=>x.alive&&x.age>=16&&!x.job&&!x.outHouse)[0];
          if(cand){cand.job="governor";p.governor=cand.id;p.loyalty=clamp(p.loyalty+14);}
          else p.loyalty=clamp(p.loyalty+7);},
        chron:S=>`the Crown sent one of its own blood to govern a restive province.`,
        out:"A royal household established where there had only been a tax collector. It is remarkable how much difference being visited makes."},
      {label:"Remit their dues for a term",cost:{gold:-22},fac:{provinces:+8,merchants:-4},
        effect:S=>{const p=restiveProvinces(S)[0]; if(p)p.loyalty=clamp(p.loyalty+16);},
        chron:S=>`the Crown remitted the dues of a restive province to buy back its loyalty.`,
        out:"You forgive the arrears and the resentment goes with them. Expensive, and it teaches a lesson somebody else will try to learn from."},
      {label:"Garrison the province and collect by force",cost:{gold:-12,arms:-3},fac:{provinces:-9,officers:+3},
        effect:S=>{const p=restiveProvinces(S)[0]; if(p)p.loyalty=clamp(p.loyalty-6);},
        chron:S=>`the Crown answered provincial discontent with a garrison and a tax column.`,
        out:"The money comes in. So does the reason they wanted to stop paying in the first place."},
      {label:"Ignore it — the country always grumbles",cost:{stability:-3},fac:{provinces:-6},
        effect:S=>{const p=restiveProvinces(S)[0]; if(p)p.loyalty=clamp(p.loyalty-8);},
        chron:S=>`the Crown ignored the discontent of a distant province.`,
        out:"Nothing happens this year. Something is quite clearly going to happen in another one."}]},
  { id:"secession",w:9,freq:1,when:S=>!!secedingProvince(S),
    title:S=>`${secedingProvince(S).name} Renounces the Crown`,
    text:S=>{const p=secedingProvince(S);
      return `It is done in daylight and with paperwork. The estates of ${p.name} met at ${p.seat}, read a declaration that had clearly been drafted some time ago, and struck the crown's arms from the courthouse door. There is no army marching. There is simply a part of the realm that has stopped being part of the realm.`;},
    choices:[
      {label:"March, and bring them back by force",
        resolve:S=>{ const p=secedingProvince(S);
          if(S.military>=52&&S.facs.officers.mood>=48){
            return {cost:{arms:-12,gold:-26,stability:-8},fac:{provinces:-10,officers:+4},
              effect:S2=>{const q=secedingProvince(S2); if(q){q.loyalty=clamp(q.loyalty+22);q.unrest=0;}},
              chron:S2=>`${p.name} renounced the Crown and was brought back into the realm at the point of the sword.`,
              out:`The columns go in and the declaration is burned in the square at ${p.seat}. ${p.name} is yours again — sullen, garrisoned, and expensive to keep. You have bought perhaps a generation.`,fortune:"good"};}
          return {cost:{arms:-16,gold:-30,stability:-14},fac:{provinces:-12,officers:-8},
            effect:S2=>{const q=secedingProvince(S2); if(q)loseProvince(S2,q); S2.legitPen=(S2.legitPen||0)+10;},
            chron:S2=>`the Crown marched against seceding ${p.name} and was beaten; the province was lost, and the losing was public.`,
            out:`The army goes in and does not come back out with the province. ${p.name} is gone, and now everyone has watched the crown fail at something it announced it would do. That is the more expensive loss.`,fortune:"bad"};}},
      {label:"Let them go, and salvage what terms you can",cost:{stability:-9},fac:{provinces:-5,merchants:+3},
        effect:S=>{const p=secedingProvince(S); if(p)loseProvince(S,p); S.legitPen=(S.legitPen||0)+5;},
        chron:S=>`the Crown let a seceding province depart, taking terms rather than casualties.`,
        out:"Envoys, a treaty of commerce, a face-saving phrase about ancient friendship. The realm is permanently smaller and permanently poorer — and it did not have to bury anyone to find that out."}]},
  /* ================= RUPTURE: BANKRUPTCY CAPITULATION ================= */
  { id:"debt_warning",w:1.5,freq:2,when:S=>debtPressure(S)>=4&&debtPressure(S)<14,
    title:"The Bankers Ask for a Private Word",
    text:S=>`They are unfailingly polite about it. The interest is being serviced with borrowing; the borrowing is being serviced with more borrowing; and the gentlemen of the exchange would like to know — privately, before anyone else asks publicly — what the Crown intends to do about it.`,
    choices:[
      {label:"Retrench — cut the household and the establishment",cost:{gold:+22,stability:-6},fac:{aristocracy:-8,officers:-6},
        effect:S=>{S._debtYears=Math.max(0,(S._debtYears||0)-8);S._armyUpkeep=Math.max(0,(S._armyUpkeep||0)-3);},
        chron:S=>`the Crown retrenched sharply to hold off its creditors.`,
        out:"Pensions stopped, offices left vacant, regiments quietly under strength. Ugly, unpopular, and it buys you years."},
      {label:"Sell offices and honours for ready money",cost:{gold:+30},fac:{aristocracy:+4,merchants:-6},
        effect:S=>{S._debtYears=Math.max(0,(S._debtYears||0)-5);S._costMod=(S._costMod||1)*1.06;},
        chron:S=>`the Crown sold offices and honours to stave off its creditors.`,
        out:"Money now, government by the highest bidder later. Every office you sell is one you cannot use."},
      {label:"Borrow again and say nothing",cost:{stability:-3},
        effect:S=>{S._debtYears=(S._debtYears||0)+3;},
        chron:S=>`the Crown answered its creditors with fresh borrowing.`,
        out:"Another loan on worse terms. The polite gentlemen go away. They will not be polite indefinitely."}]},
  { id:"capitulation",w:9,freq:1,when:S=>debtPressure(S)>=14,
    title:"The Crown Cannot Pay",
    text:S=>`The payment is missed, and this time it is missed publicly. Within a month the creditors and the estates are sitting in the same room — which has never once happened in this realm's history for a good reason — and they have drafted terms rather than a petition.`,
    choices:[
      {label:"Accept the settlement",
        resolve:S=>{
          const hasCh=S.gov.institutions.length>0;
          return {cost:{stability:+4},fac:{merchants:+8,aristocracy:+5,peasantry:-4},
            effect:S2=>{
              S2._landsSold=Math.min(0.45,(S2._landsSold||0)+0.18);
              S2.treasury=Math.max(S2.treasury,-20); S2.debt=0; S2._debtYears=0;
              if(hasCh){ const inst=S2.gov.institutions[0];
                transferPower(S2,inst,Math.min(14,S2.gov.crown.power));
                if(!inst.rights.includes("tax"))inst.rights.push("tax");
              } else { forceChamber(S2,16); }
              S2.legitPen=(S2.legitPen||0)+6;
            },
            chron:S2=>`unable to pay, the Crown accepted the creditors' settlement: lands sold, and the purse placed under a standing chamber.`,
            out:`The debts are cleared and the price is written into the constitution. Crown lands are sold off — your receipts are permanently smaller — and ${hasCh?"the chamber takes the power of the purse, which no crown has ever taken back easily":"a standing chamber is called into being to hold the purse, which was precisely what you had spent a century avoiding"}. You are still sovereign. You are sovereign of less.`,fortune:"bad"};}},
      {label:"Repudiate the debt entirely",
        resolve:S=>({cost:{stability:-18},fac:{merchants:-24,aristocracy:-10,provinces:-6},
          effect:S2=>{S2.debt=0;S2.treasury=Math.max(S2.treasury,-10);S2._debtYears=0;
            S2._creditBonus=0; S2._costMod=(S2._costMod||1)*1.18; S2.legitPen=(S2.legitPen||0)+12;
            provinces(S2).forEach(p=>{p.loyalty=clamp(p.loyalty-8);});},
          chron:S2=>`the Crown repudiated its debts outright; credit died, and everything the realm bought thereafter cost more.`,
          out:"You simply refuse to pay. The bankers are ruined, the exchange closes, and nobody will lend to this crown again in your lifetime — which means everything from now on is paid for in cash, at a premium, forever. It is not a settlement. It is a wound you chose."})}]},

  /* ================= RUPTURE: ARISTOCRATIC REACTION ================= */
  { id:"react_warning",w:1.5,freq:2,when:S=>reactionPressure(S)>=4&&reactionPressure(S)<13,
    title:"The Great Houses Meet for the Hunting",
    text:S=>`Eleven of the first families are gathered at a country seat, ostensibly for the season. Their sons command regiments. Their chaplains preach to half the realm. The invitations went out before anyone thought to inform the court, and no one has thought to inform it since.`,
    choices:[
      {label:"Buy them back — honours, offices, exemptions",cost:{gold:-30},fac:{aristocracy:+14,clergy:+8,peasantry:-5},
        effect:S=>{S._reactYears=Math.max(0,(S._reactYears||0)-9);},
        chron:S=>`the Crown bought back the loyalty of the great houses with honours and exemptions.`,
        out:"Garters, sinecures and a quiet promise about the land tax. Everything you conceded here you will want back in fifty years."},
      {label:"Break the leading house as an example",cost:{stability:-9},fac:{aristocracy:-12,clergy:-5,peasantry:+7,officers:+4},
        effect:S=>{S._reactYears=(S._reactYears||0)+3;},
        chron:S=>`the Crown attainted the leading house of the realm to cow the rest.`,
        out:"Lands forfeit, a title extinguished, a family scattered. The other ten go home very quiet — and very clear about what the crown is now prepared to do."},
      {label:"Let them hunt",cost:{stability:-2},
        effect:S=>{S._reactYears=(S._reactYears||0)+4;},
        chron:S=>`the Crown took no notice of the gathering of the great houses.`,
        out:"They hunt. They talk. They go home. The invitations for next season go out earlier."}]},
  { id:"reaction",w:9,freq:1,when:S=>reactionPressure(S)>=13,
    title:"The Restoration of the Old Order",
    text:S=>`They do not call it a rebellion, because that would require admitting there is something to rebel against. The great houses and the bishops simply announce that the realm has been misgoverned, that the ancient constitution will be restored, and that the crown will be worn by someone more attentive to it.`,
    choices:[
      {label:"Resist — call the realm to the crown's defence",
        resolve:S=>{
          const strong=S.military>=50&&(S.facs.officers.mood>=50||S.facs.peasantry.mood>=55);
          if(strong) return {cost:{stability:-12,arms:-9,gold:-20},fac:{aristocracy:-16,clergy:-10,officers:+6,peasantry:+8},
            effect:S2=>{S2._reactYears=0;S2.facs.aristocracy.strength=clamp(S2.facs.aristocracy.strength-10);},
            chron:S2=>`the great houses moved to restore the old order and were broken; the aristocracy never recovered its former weight.`,
            out:"You call, and the realm comes — the regiments, the towns, and a startling number of people who have their own reasons to dislike dukes. The rising collapses. The old families are diminished permanently, which is a rare thing to be able to say.",fortune:"good"};
          return {cost:{stability:-16},fac:{aristocracy:+10,clergy:+8},
            effect:S2=>{doReaction(S2);},
            chron:S2=>`the Crown resisted the reaction and lost; the old order was restored over its body.`,
            out:"You call, and not enough comes. The gates open, the reforms are struck out one by one, and a more agreeable head is found for the crown.",fortune:"bad"};}},
      {label:"Submit, and keep what can be kept",cost:{stability:-8},fac:{aristocracy:+12,clergy:+9,merchants:-8},
        effect:S=>{doReaction(S);},
        chron:S=>`the Crown submitted to the reaction; the ancient constitution was restored and the throne changed hands.`,
        out:"You sign what is put in front of you. The chambers lose what they were given, the statutes are repealed, and the crown passes to someone the great houses find more restful. You are still the will behind the throne — it is simply a different throne now."}]},
  /* ================= RUPTURE: THE COUP ================= */
  { id:"barracks_warning",w:1.6,freq:3,when:S=>isMonarchy(S)&&pressureOf(S,"military")>=48&&pressureOf(S,"military")<74,
    title:"The Officers Decline Their Invitations",
    text:S=>`Three generals were expected at court and none came. A regiment moved garrison without an order anyone will admit to writing. At an officer's funeral last month there were more colonels present than the war office knew were in the country, and they stayed talking a long while after the burial.`,
    choices:[
      {label:"Pay the army what it is owed, in full and publicly",cost:{gold:-32,stability:+4},fac:{officers:+14},
        effect:S=>{S.pressure.military=Math.max(0,(S.pressure.military||0)-22);S._militaryLeaned=Math.max(0,(S._militaryLeaned||0)-4);},
        chron:S=>`the Crown paid the army in full and in public, and the whispering in the barracks stopped for a while.`,
        out:"Chests carried through the streets under escort, deliberately visible. Soldiers who are paid do not need to be watched — which is fortunate, because you cannot watch them."},
      {label:"Break up the cliques — post the ringleaders apart",cost:{gold:-14,stability:-4},fac:{officers:-9},
        effect:S=>{S.pressure.military=Math.max(0,(S.pressure.military||0)-14);S.military=clamp(S.military-5);},
        chron:S=>`the Crown scattered the leading officers to distant commands.`,
        out:"Six colonels posted to six frontiers. It works — they cannot conspire by letter as well as they could over dinner — and the army is a little worse at its job for it."},
      {label:"Give them what they want — a freer hand and more of it",cost:{stability:+3},fac:{officers:+12,merchants:-6,peasantry:-6},
        effect:S=>{S._armyUpkeep=(S._armyUpkeep||0)+4;S.military=clamp(S.military+8);S.pressure.military=Math.max(0,(S.pressure.military||0)-8);},
        chron:S=>`the Crown answered the army's discontent by giving it more of everything.`,
        out:"More men, more money, more latitude. The generals are delighted. You have quieted them by making them larger, which is a solution with a shape to it."},
      {label:"Take no notice",cost:{stability:-2},
        effect:S=>{S.pressure.military=Math.min(100,(S.pressure.military||0)+7);},
        chron:S=>`the Crown took no notice of the officers' quiet meetings.`,
        out:"Nothing happens. The meetings continue, and the attendance improves."}]},
  { id:"coup",w:12,freq:1,when:S=>isMonarchy(S)&&pressureOf(S,"military")>=74,
    title:"The Regiments Do Not Disperse",
    text:S=>`The parade was to have ended at noon. At noon the regiments were still standing in the square, and by two o'clock they had been joined by two more. There is no proclamation, no manifesto, no demand — simply an army that has stopped going home, and a palace that has noticed how few men are guarding it.`,
    choices:[
      {label:"Stand on the crown's authority and order them to disperse",
        resolve:S=>{
          if(S.facs.officers.mood>=52&&legitimacy(S)>=45){
            return {cost:{stability:-8},fac:{officers:+6},
              effect:S2=>{S2.pressure.military=Math.max(0,(S2.pressure.military||0)-38);S2._militaryLeaned=0;},
              chron:S2=>`the Crown faced down the standing regiments, and they went home.`,
              out:"You go out to them yourself, without guards, and give the order in a voice that expects to be obeyed. It is obeyed. It will not be twice.",fortune:"good"};}
          const gen=newGeneral(S);
          return {effect:S2=>{S2._pendingCoup=gen;},
            chron:S2=>`the Crown ordered the regiments to disperse and was ignored; the army took the state.`,
            out:`The order is read out. Nothing happens. A colonel steps forward, apologises with real embarrassment, and explains that ${gen.name} would like to speak with you.`,fortune:"bad"};}},
      {label:"Buy the generals off before the day ends",cost:{gold:-46},
        resolve:S=>{
          if(S.treasury<40) return {cost:{stability:-6},effect:S2=>{S2._pendingCoup=newGeneral(S2);},
            chron:S2=>`the Crown tried to buy the generals and could not afford them.`,
            out:"The offer is made and the sum is heard, and there is a pause that goes on slightly too long. Then a very junior officer laughs.",fortune:"bad"};
          return {cost:{gold:-46,stability:-5},fac:{officers:+10,merchants:-8},
            effect:S2=>{S2.pressure.military=Math.max(0,(S2.pressure.military||0)-30);},
            chron:S2=>`the Crown bought the loyalty of its generals on the day of the parade, at enormous cost.`,
            out:"Estates, arrears, three dukedoms and a great deal of cash. The regiments march home. You have bought the army from itself with its own back pay — and taught it exactly what it is worth."};}},
      {label:"Let it come",
        resolve:S=>({effect:S2=>{S2._pendingCoup=newGeneral(S2);},
          chron:S2=>`the Crown made no answer to the standing regiments, and the army took the state.`,
          out:"You do nothing, which is at least dignified. By evening the palace guard has been relieved by men who were not sent for.",fortune:"bad"})}]},
  { id:"jacquerie",w:8,freq:2,when:S=>{const t=transitionReady(S);return !!(t&&t.jacquerie);},
    title:"The Country Rises",
    text:S=>`It begins in three districts at once, which means it did not begin by accident. Manor houses burning, rent rolls burning, a bailiff hanged from his own gate. They have no programme and no leaders anybody can negotiate with — this is an age before either. They simply want it to stop.`,
    choices:[
      {label:"Put it down",cost:{gold:-18,arms:-6,stability:+6},fac:{peasantry:-16,workers:-12,aristocracy:+9},
        effect:S=>{bumpPressure(S,"radical",-30);provinces(S).forEach(p=>{if(!p.core)p.loyalty=clamp(p.loyalty-5);});},
        chron:S=>`the rising of the country was put down, and the assizes were busy for a year afterward.`,
        out:"Cavalry against billhooks; it takes a season and it is never in doubt. The rising is broken, the ringleaders are hanged in their own villages, and nothing whatever has been settled."},
      {label:"Buy it off — remit the dues and hear the grievances",cost:{gold:-34,stability:+4},fac:{peasantry:+14,aristocracy:-10},
        effect:S=>{bumpPressure(S,"radical",-38);provinces(S).forEach(p=>{p.loyalty=clamp(p.loyalty+8);});},
        chron:S=>`the Crown bought off the rising of the country with remissions and a hearing.`,
        out:"Arrears forgiven, three of the worst stewards dismissed, a commission that will report in due course. They go home. It is expensive and it works, and the great houses will not forgive it."},
      {label:"Do nothing and let it burn out",cost:{stability:-14},fac:{peasantry:-8,aristocracy:-12,provinces:-10},
        effect:S=>{lowerDevelopment(S,5);bumpPressure(S,"radical",-12);},
        chron:S=>`the rising of the country burned itself out over three years, taking a good deal of the country with it.`,
        out:"It exhausts itself eventually, the way fires do. What is left is a countryside that has learned it can burn things, and a nobility that has learned the crown will not protect them."}]},
  /* ================= DISASTERS OF THE INDUSTRIAL AGES ================= */
  { id:"pit_disaster",w:1.2,freq:4,when:S=>eraIdx(S)>=5,title:"The Pit",
    text:S=>`Firedamp, at four in the morning, two hundred fathoms down. The cage brings up what it can. By afternoon the whole district is standing at the head of the shaft in silence, and the owners' agent has said something unforgivable to a newspaper.`,
    choices:[
      {label:"Compensate the families and inspect every pit in the realm",cost:{gold:-28,stability:+5},fac:{workers:+14,peasantry:+8,merchants:-10},
        effect:S=>{S._upkeepAge=(S._upkeepAge||0)+2;bumpPressure(S,"radical",-14);},
        chron:S=>`after the disaster at the pit, the Crown paid the families and set inspectors over every mine in the realm.`,
        out:"Money to the widows within the month and an inspectorate that will be resented for a century. The owners are furious. Nobody else is."},
      {label:"Call it an act of God",cost:{stability:-9},fac:{workers:-18,merchants:+6},
        effect:S=>{bumpPressure(S,"radical",16);},
        chron:S=>`the government declared the pit disaster an act of God, and the coalfield did not forget it.`,
        out:"The inquiry finds nobody at fault, which everybody expected and nobody forgives. The combinations gain more members that year than in the previous ten."}]},
  { id:"general_strike",w:1.3,freq:4,when:S=>eraIdx(S)>=6&&S.facs.workers&&S.facs.workers.present&&S.facs.workers.mood<48,
    title:"The Works Stand Idle",
    text:S=>`It began in one trade and by the end of the week it is all of them. No coal moves, no trains run, and the capital is discovering how many things it assumed would simply happen. The committee asks for recognition, hours and a wage.`,
    choices:[
      {label:"Negotiate — recognize them and settle",cost:{gold:-24,stability:+6},fac:{workers:+18,merchants:-14},
        effect:S=>{S.civil=S.civil||{};S.civil.unions=clamp((S.civil.unions||45)+16);bumpPressure(S,"radical",-18);},
        chron:S=>`the great strike ended in recognition and a settlement.`,
        out:"You meet them, which is the concession that matters; the hours and the wage are details. The mills restart. Something has changed permanently and everyone in the room knows it."},
      {label:"Break it with troops",cost:{gold:-16,arms:-4,stability:-12},fac:{workers:-24,officers:+5,merchants:+10},
        effect:S=>{bumpPressure(S,"radical",22);bumpPressure(S,"military",8);S.legitPen=(S.legitPen||0)+8;},
        chron:S=>`the great strike was broken by soldiers, and there were deaths in the streets of the manufacturing towns.`,
        out:"The works restart under guard. There is a number of dead and it will be printed, sung, and taught to children who were not born yet."},
      {label:"Wait them out — they have no savings",cost:{stability:-7},fac:{workers:-12,merchants:-6},
        effect:S=>{lowerDevelopment(S,4);bumpPressure(S,"radical",10);},
        chron:S=>`the government sat out the great strike; hunger ended it after eleven weeks.`,
        out:"Eleven weeks. They go back on the old terms, having learned exactly what they are worth to you and exactly how long they can last. Both numbers are now known to both sides."}]},
  { id:"crash",w:1.1,freq:5,when:S=>eraIdx(S)>=5&&(S._creditBonus||0)>=100,title:"The Crash",
    text:S=>`Railway shares, mostly. They went up for six years for no reason anybody could name and they have come down in nine days for the same reason. Banks that were sound on Monday are queues by Thursday, and a great many respectable people are ruined.`,
    choices:[
      {label:"Guarantee the deposits and let the speculators fail",cost:{gold:-34,stability:+4},fac:{merchants:-6,peasantry:+8},
        effect:S=>{S._creditBonus=Math.max(0,(S._creditBonus||0)-40);},
        chron:S=>`the state guaranteed the deposits through the crash and let the speculators go under.`,
        out:"Small savers are made whole and the men who caused it are not. It is expensive, popular, and sets a precedent that will be invoked at you forever."},
      {label:"Rescue the great houses of finance",cost:{gold:-40},fac:{merchants:+12,workers:-14,peasantry:-12},
        effect:S=>{bumpPressure(S,"radical",14);S.legitPen=(S.legitPen||0)+6;},
        chron:S=>`the state rescued the banking houses, and the country noticed who had been rescued.`,
        out:"Credit is restored within a season. So is the conviction, in every town in the realm, that there is one law for the exchange and another for everybody else."},
      {label:"Let it burn out",cost:{stability:-14},fac:{merchants:-18},
        effect:S=>{lowerDevelopment(S,8);S._creditBonus=Math.max(0,(S._creditBonus||0)-90);},
        chron:S=>`the crash was left to run its course, and took a decade of growth with it.`,
        out:"Three hundred firms, eleven banks, and a great deal of the confidence that made the last twenty years possible. It will come back. It will take longer than you have."}]},
  { id:"cholera",w:1.1,freq:5,when:S=>eraIdx(S)>=5&&!ownsAdv(S,"sanitary"),title:"Cholera in the New Towns",
    text:S=>`It comes up through the courts and cellars of the manufacturing districts, where twelve thousand people share a water supply nobody planned. The physicians argue about miasma. The undertakers do not have time to argue.`,
    choices:[
      {label:"Build sewers and a clean supply, whatever it costs",cost:{gold:-38,stability:+6},fac:{workers:+12,peasantry:+10},
        effect:S=>{S._upkeepAge=(S._upkeepAge||0)+4;S._mortalityEase=(S._mortalityEase||0)+0.2;raiseDevelopment(S,5);},
        chron:S=>`cholera in the new towns was answered with sewers and clean water at the public charge.`,
        out:"Enormous, filthy, unglamorous work that will be finished long after you are gone. It is the single most useful thing this government will ever do."},
      {label:"Quarantine the districts",cost:{gold:-14,stability:-6},fac:{workers:-12,merchants:-6},
        effect:S=>{lowerDevelopment(S,4);bumpPressure(S,"radical",12);},
        chron:S=>`the afflicted districts were cordoned off and left to it.`,
        out:"Soldiers at the end of every street and food passed across a line. It works, in the sense that it does not spread. The people inside are quite clear about what has been done to them."}]},
  { id:"chamber_hunger",w:0.9,freq:5,when:S=>!pmGoverns(S)&&S.gov.institutions.length>0&&S.gov.institutions[0].power<30,
    title:S=>`The ${S.gov.institutions[0].name} Demands More`,
    text:S=>`A chamber, once summoned, does not stay grateful. The ${S.gov.institutions[0].name} has drawn up a formal address: it holds too little power for the burdens laid upon it, and it wants more. The address is polite. The mood behind it is not.`,
    choices:[
      {label:"Grant a further measure of power",cost:{stability:+3},fac:{aristocracy:+5,clergy:+2},
        effect:S=>{transferPower(S,S.gov.institutions[0],8);},
        chron:S=>`the ${S.gov.institutions[0].name} pressed for a greater share of power, and the Crown yielded a measure gracefully.`,
        out:"You grant it before it must be taken. The chamber notes — approvingly — which kind of crown it serves."},
      {label:"Refuse the address",cost:{stability:-4},fac:{aristocracy:-6,clergy:-4},
        chron:S=>`the Crown refused the chamber's address for greater power; the refusal was filed, and remembered.`,
        out:"Refused with full ceremony. The address goes into the chamber's records — the kind of document that gets re-read in worse years."}]},
  { id:"commons_forced",w:6,freq:2,when:S=>{ if((S._commonsDismissed||0)>=3&&!S.gov.institutions.some(i=>i.composition!=="nobility")){ askReform(S,"lower_house",2); return true; } return false; },
    title:"They Have Stopped Petitioning",
    text:S=>`There is no petition this time. The towns have elected delegates of their own, met without leave, and sent word of what they have resolved rather than what they request. The phrase going round is that they asked three times.`,
    choices:[
      {label:"Seat them — call a chamber of the commons",cost:{stability:+5},fac:{merchants:+10,peasantry:+10,aristocracy:-8},
        effect:S=>{S._commonsDismissed=0;
          const inst={id:"ch"+S.gov.institutions.length,name:culture(S).inst[1]||"The Commons",composition:"commons",power:0,rights:["petition","tax"]};
          S.gov.institutions.push(inst); transferPower(S,inst,Math.min(14,S.gov.crown.power));},
        chron:S=>`the towns convened without leave, and the Crown chose to seat them rather than scatter them.`,
        out:"You give it a room, a name and a mace, which turns an illegal assembly into an institution — and institutions can be bargained with. It is the cheapest thing you will do this century."},
      {label:"Scatter them by force",cost:{stability:-14,arms:-4},fac:{merchants:-12,peasantry:-14,officers:+3,reformers:-16},
        effect:S=>{S.legitPen=(S.legitPen||0)+9;leanOnArmy(S,2);
          if(S.facs.reformers)S.facs.reformers.strength=clamp(S.facs.reformers.strength+10);
          provinces(S).forEach(p=>{if(!p.core)p.loyalty=clamp(p.loyalty-7);});},
        chron:S=>`the Crown scattered the unauthorized assembly of the towns by force.`,
        out:"The hall is cleared in an afternoon. What was a demand becomes a grievance, what was a delegation becomes a movement, and the countryside hears about it within the month."}]},
  { id:"estates_cry",w:8,freq:3,
    when:S=>isMonarchy(S)&&!S.gov.institutions.length
      &&(eraIdx(S)>=2||pressureOf(S,"constitutional")>=45),
    title:"The Realm Asks for a Hearing",
    text:S=>`The great houses, the towns and the church have between them found a single thing to agree on: that the ${crownWord(S)} taxes them without asking, and that this was tolerable when the realm was smaller. A petition has been drawn and signed. It asks for an assembly — advisory, occasional, summoned at the ${crownWord(S)}'s pleasure. It asks very politely, this time.`,
    choices:[
      {label:"Receive the petition; the question is opened",
        cost:{stability:+3},fac:{aristocracy:+4,merchants:+5,clergy:+3},
        effect:S=>{ askReform(S,"summon_estates",1); S._estatesAsked=true; },
        chron:S=>`the petition for an assembly was received with warmth, and the question was opened that would not again close.`,
        out:"Received, read, and answered with a courtesy that commits you to nothing. But the question is on the record now, and questions on the record have a way of becoming statutes."},
      {label:"Return it unread",
        cost:{stability:-5},fac:{merchants:-7,aristocracy:-4,clergy:-3},
        effect:S=>{ S._estatesDismissed=(S._estatesDismissed||0)+1;
          bumpPressure(S,"constitutional",9);
          askReform(S,"summon_estates",(S._estatesDismissed>=3)?2:1);
          S._estatesAsked=true; },
        chron:S=>`the petition for an assembly was returned unread; the signatures were copied out first.`,
        out:"Returned, unopened, with a note about precedent. The signatories are not surprised and were not really expecting otherwise. They keep the list."}
    ]},
  { id:"commons_cry",w:0.8,freq:6,when:S=>{ const ok=S.gov.institutions.length>0&&!S.gov.institutions.some(i=>i.composition!=="nobility")&&(S.facs.merchants.strength+S.facs.peasantry.strength)>=95; if(ok)askReform(S,"lower_house",1); return ok; },
    title:"The Cry for a Commons",
    text:S=>`The realm below the great houses has grown too big to ignore: guild money, market towns, a countryside that reads. Petitions arrive from forty towns with one demand — a chamber of their own.`,
    choices:[
      {label:"Receive the petitioners warmly",cost:{stability:+4},fac:{merchants:+4,peasantry:+4,aristocracy:-3},
        chron:S=>`the Crown received the towns' great petition for a commons with warmth, and the question was opened that would not again close.`,
        out:"You make no promise — but you let them be heard, at length, in public. The reform now has a constituency. (Seat a lower chamber when you're ready.)"},
      {label:"Dismiss it — the estates speak for the realm",cost:{stability:-5},fac:{merchants:-6,peasantry:-7},
        effect:S=>{S._commonsDismissed=(S._commonsDismissed||0)+1;
          if(S._commonsDismissed>=2){S.facs.reformers.present=true;S.facs.reformers.strength=clamp(S.facs.reformers.strength+12);}},
        chron:S=>`the Crown dismissed the cry for a commons; the towns went home and began keeping their own counsel.`,
        out:"The petitioners are sent home with courtesies. What they build next will not be a petition."}]},
  { id:"restoration",w:0.8,freq:6,when:S=>!!S.pm&&S.gov.crown.power>=40&&S.gov.crown.power<50,title:"The Crown Demands Restoration",
    text:S=>`${styled(S,S.monarch)} has had enough of ministers. With the officers listening and the old families nodding, the palace formally demands its powers returned. This is the strongest a crown can be while you still govern — and it knows it.`,
    choices:[
      {label:"Concede a measure of power back",cost:{stability:+5},fac:{aristocracy:+6},
        effect:S=>{powerToCrown(S,S.gov.institutions[0],8);},
        chron:S=>`the ministry conceded powers back to the Crown, and the arrow of history bent, briefly, the other way.`,
        out:"You hand a slice of the prerogative back. The palace glows; the chamber grumbles; the storm passes — this time."},
      {label:"Refuse — and dare the palace to act",
        resolve:S=>{ if(S.military>=45&&S.facs.officers.mood>=48){
            return {cost:{stability:-8},effect:S2=>{S2.gov.crown.power=Math.min(S2.gov.crown.power,20);const diff=100-(S2.gov.crown.power+S2.gov.institutions.reduce((a,i)=>a+i.power,0));if(diff>0)S2.gov.institutions[0].power+=diff;},fac:{officers:+5,aristocracy:-8},
              chron:S2=>`the Crown moved against its ministry and the army did not follow; the attempted restoration broke the throne down to a figurehead.`,
              out:"The palace plays its hand — and the regiments stay in their barracks, awaiting YOUR orders. The restoration collapses in a week. The Crown will never be this strong again."};}
          return {cost:{stability:-14,arms:-8},effect:S2=>{powerToCrown(S2,S2.gov.institutions[0],22);},fac:{officers:-6,aristocracy:+8},
            chron:S2=>`the Crown moved against its ministry with the officers at its back, and won; power flowed back to the palace at bayonet-point.`,
            out:"The palace plays its hand — and the officers choose the Crown. Soldiers in the lobby, the mace carried out. You keep the office; the office keeps much less."};}},
      {label:"Buy the palace's patience",cost:{gold:-30},fac:{aristocracy:+4},
        chron:S=>`the ministry bought the Crown's patience with a settlement of revenues and honours.`,
        out:"A civil list, some honours, a yacht. Undignified, affordable, effective."}]},
  { id:"abdication_cry",w:0.9,freq:6,when:S=>!pmGoverns(S)&&legitimacy(S)<25&&!!heirOf(S)&&!S.regency,title:"The Cry for Abdication",
    text:S=>`The realm has stopped pretending. In the chambers, the taverns and the great houses alike, one word travels: abdicate. ${heirOf(S).name} waits, carefully saying nothing.`,
    choices:[
      {label:"Lay down the crown in favour of the heir",cost:{stability:+8},
        effect:S=>{S._abdicate=true;},
        chron:S=>`${styled(S,S.monarch)}, unloved and unlamented, laid down the crown in favour of the heir.`,
        out:"The instrument is signed without ceremony — and the sovereign remains sovereign until the season closes, because the machinery of a realm cannot be stopped mid-turn. By year's end the crown sits on a fresher head, and the realm exhales."},
      {label:"Refuse — the crown is not the mob's to demand",cost:{stability:-6},
        effect:S=>{S.legitPen=(S.legitPen||0)+4;},
        chron:S=>`the Crown refused the realm's demand for abdication, and wore its unpopularity like armour.`,
        out:"You stay. The word doesn't stop travelling."}]},
  { id:"crown_meddles",w:0.9,freq:4,when:S=>pmGoverns(S),title:"The Crown Meddles",
    text:S=>`${styled(S,S.monarch)} has taken up a pet cause and presses the ministry to fund it — publicly enough that refusal will be noticed.`,
    choices:[
      {label:"Indulge the sovereign",cost:{gold:-12},fac:{aristocracy:+4},
        chron:S=>`the ministry indulged the Crown's enthusiasm, and palace and cabinet kept their peace.`,
        out:"The scheme is funded, the sovereign delighted, the constitutional question left politely unasked."},
      {label:"Decline — the ministry sets policy now",cost:{stability:-3},fac:{aristocracy:-3},
        chron:S=>`the ministry declined the Crown's request, and the palace learned where policy was now made.`,
        out:"A frosty audience. The refusal stands — and so, a little more clearly, does the new order of things."}]},
  { id:"foreign_match",w:0.7,freq:5,title:"A Foreign Crown Proposes Alliance",
    text:S=>`An envoy from a powerful neighbour proposes a binding alliance — sealed, as such things are, by marriage and obligation.`,
    choices:[
      {label:"Accept the alliance",cost:{arms:+6},fac:{aristocracy:+3,officers:+3},
        chron:S=>`${S.nation} bound itself to a powerful neighbour; the alliance outlasted the affection, as alliances do.`,
        out:"Vows exchanged with great pomp. You have a friend — and its enemies."},
      {label:"Decline and keep your hands free",cost:{stability:+2},fac:{merchants:+2},
        chron:S=>`${S.nation} declined the offered alliance and kept its independence unencumbered.`,
        out:"Refused with every courtesy. You owe no one, and no one owes you."}]},
];
function eligibleEvents(S){
  return EVENTS.filter(e=>{
    if(e.when&&!e.when(S))return false;
    const last=S.eventLast[e.id];
    if(last!=null){ if(e.freq===Infinity)return false; if(S.turn-last<e.freq)return false; }
    return true;
  });
}
